resolver: lts-13.1
packages:
- .
- location:
    git: https://github.com/syallop/Join-Language.git
    commit: b1f9a75a6ca322e424952e1f422232ac5f018745
  extra-dep: true

- location:
    git: https://github.com/syallop/DSL-Compose.git
    commit: 5a95ae855f3291aa3193a7424892035226b10d2f
  extra-dep: true

- location:
    git: https://github.com/syallop/NonZero.git
    commit: 6e63680e48383cbe6624028b7216c4ebfe208a8b
  extra-dep: true

- location:
    git: https://github.com/syallop/DHT.git
    commit: 11040d7b77856002c60970ca1dee2668b97577a8
  extra-dep: true

- location:
    git: https://github.com/syallop/DHT-NS.git
    commit: 4ea38ad0e96565bbf47b1140a1db6913c01e1c03
  extra-dep: true
extra-deps:
flags: {}
extra-package-dbs: []
