resolver: lts-8.9
packages:
- .
- ../
- location: https://github.com/syallop/Join-Language/archive/master.zip
  extra-dep: true
- location: https://github.com/syallop/DSL-Compose/archive/master.zip
  extra-dep: true
- location: https://github.com/syallop/NonZero/archive/master.zip
  extra-dep: true
- location: https://github.com/syallop/DHT/archive/master.zip
  extra-dep: true
- location: https://github.com/syallop/DHT-NS/archive/master.zip
  extra-dep: true
extra-deps:
flags: {}
extra-package-dbs: []

